# Application
quarkus.application.name=zelus
quarkus.application.version=1.0.0

# Root path
quarkus.http.root-path=/zelus

# REST base path
quarkus.rest.path=/api

# Quinoa (Angular SPA)
quarkus.quinoa.enable-spa-routing=true

# Hibernate ORM
quarkus.hibernate-orm.database.generation=drop-and-create

# File uploads
quarkus.http.body.uploads-directory=uploads
quarkus.http.limits.max-form-attribute-size=10M

# CORS (dev)
quarkus.http.cors=true
